pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REGISTRY = '631749620851.dkr.ecr.ap-south-1.amazonaws.com'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh '''
                    set -eux

                    cd product-service
                    npm install
                    npm test

                    cd ../order-service
                    npm install
                    npm test
                '''
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                    set -eux

                    docker build \
                      -t $ECR_REGISTRY/cloudshop/product-service:$IMAGE_TAG \
                      product-service

                    docker build \
                      -t $ECR_REGISTRY/cloudshop/order-service:$IMAGE_TAG \
                      order-service

                    docker build \
                      -t $ECR_REGISTRY/cloudshop/frontend:$IMAGE_TAG \
                      frontend
                '''
            }
        }

        stage('Push Images') {
            steps {
                sh '''
                    set -eux

                    aws sts get-caller-identity

                    aws ecr get-login-password --region $AWS_REGION |
                    docker login \
                      --username AWS \
                      --password-stdin $ECR_REGISTRY

                    docker push $ECR_REGISTRY/cloudshop/product-service:$IMAGE_TAG
                    docker push $ECR_REGISTRY/cloudshop/order-service:$IMAGE_TAG
                    docker push $ECR_REGISTRY/cloudshop/frontend:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh '''
                    set -eux

                    aws eks update-kubeconfig \
                      --region $AWS_REGION \
                      --name my-eks

                    kubectl -n ecommerce set image deployment/product-service \
                      product-service=$ECR_REGISTRY/cloudshop/product-service:$IMAGE_TAG

                    kubectl -n ecommerce set image deployment/order-service \
                      order-service=$ECR_REGISTRY/cloudshop/order-service:$IMAGE_TAG

                    kubectl -n ecommerce set image deployment/frontend \
                      frontend=$ECR_REGISTRY/cloudshop/frontend:$IMAGE_TAG

                    kubectl -n ecommerce rollout status deployment/product-service
                    kubectl -n ecommerce rollout status deployment/order-service
                    kubectl -n ecommerce rollout status deployment/frontend
                '''
            }
        }
    }

    post {
        always {
            sh 'docker image prune -f || true'
        }
    }
}

